apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-svc
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-web
